Fix error in Windows
Line 49 and 50 are missing spaces at the beginning of the code - was throwing an error in Matrix at startup:

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'DISTRIBUTION' is not defined
                                                   Traceback (most recent call last):
                                                     File "C:\Users\andyr\OneDrive\Desktop\Kodi_19_Matrix_v1\portable_data\addons\service.xbmc.versioncheck\resources\lib\runner.py", line 14, in <module>
                                                       from version_check import service  # pylint: disable=import-error
                                                     File "C:\Users\andyr\OneDrive\Desktop\Kodi_19_Matrix_v1\portable_data\addons\service.xbmc.versioncheck\resources\lib\version_check\service.py", line 49, in <module>
                                                       if not DISTRIBUTION:
                                                   NameError: name 'DISTRIBUTION' is not defined
                                                   -->End of Python script error report<--